---
- hosts: aws

  vars_files:
    - ./vars/vars.yml

  vars:
    ansistrano_deploy_to: "{{ project_deploy_dir }}"
    ansistrano_deploy_via: git
    ansistrano_git_repo: "https://github.com/boonkuaeb/ansistrano-deploy.git"
    ansistrano_git_branch: master

  roles:
    - ansistrano.deploy